### ISSUE TITLE
no image, it is as if it is not installed

### ISSUE THREAD

**Issue by yurigoul** [columbusinteractive/typo3-easycaptcha#10]
This is probably a total n00b error, but here I go - it is advertised as being easy so I hope it actually is :-)

- Installed easycaptcha using upload on my install of typo3 9.5.17 with the bootstrap_package installed.
- Included easy captcha to my static items from extensions
- added the easycaptcha element to my form and flushed the cache 

This is the result:

![Screen Shot 2020-06-17 at 19 34 46](https://user-images.githubusercontent.com/11797611/84930700-f9927580-b0d1-11ea-9fb4-9e731a944e74.png)

It is as if it is not installed - removing the extension from the template has the same result. Have moved the extension higher up, removed tts as an option, tried adding the typoscript from the configuration folder to setup and constants, removed all plugins but this one and the boot_strap package. All the same result. 

The image links to /typo3conf/ext/easycaptcha/Classes/Service/Image.php?pid=27&identifier=easycaptcha-1

Thanks in advance!

EDIT: tried installing 1.2.1 - but no dice

**Comment by yurigoul** [comment]
Could this have anything to do with the boostrap_package ? If so, how could I make this work?

**Comment by benjaminhirsch** [comment]
Hey @yurigoul, sorry for the late reply. We've tested the extension with a clean TYPO3 installation without any problems in the latest version. So I can't garantee that there is no problem in combination with any other extension. In theory - it shouldn't. ;)

What happens when you open the Image (with the link you posted) directly in the browser? Can you see a error message or is something written to the log?

**Comment by AKaravas** [comment]
I found the problem is. I have a **composer** installation and **TYPO3 v10**.

Now in the **easycaptcha/Classes/Service/Image.php** there is the following in the line 27:

``` 
   $classLoader = require dirname(__DIR__, 6) . '/vendor/autoload.php';
```
I changed the path to 
``` 
   $classLoader = require dirname(__DIR__, 6) . '/Packages/Libraries/autoload.php';
```
then i ru the dumpautoload command and it worked. 

The problem is that it can not find the **/vendor/autoload.php** file.

[Image](http://prntscr.com/uebzr7)

**Comment by benjaminhirsch** [comment]
Seems that we have to check where the vendor directory is, because currently we're expecting it to be vendor, which is the default path by composer. 

So I guess you have someting different for https://getcomposer.org/doc/06-config.md#vendor-dir set, @AKaravas in your composer.json, right?

**Comment by AKaravas** [comment]
yes we do :)

```
"config"   : {
      "vendor-dir" : "Packages/Libraries",
      "bin-dir"    : "bin"
},
```

**Comment by szerner** [comment]
I have the same issue as @yurigoul, the image doesn't render. My installation was via TER (not composer!), the static template is properly included.

The frontend renders the image as

`<img id="captcha-image" alt="" src="/typo3conf/ext/easycaptcha/Classes/Service/Image.php?pid=1&amp;identifier=easycaptcha-1">`

with dimensions of 0x0px.

If I try to open the image src in a new tab, I get an `"Oops, an error occured!"` message and the system log contains the new entry

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Unable to find a form element with the given identifier: easycaptcha-1 | ColumbusInteractive\EasyCaptcha\Exceptions\ElemenIdentifierNotFoundInForm thrown in file [...]/typo3conf/ext/easycaptcha/Classes/Exceptions/ElemenIdentifierNotFoundInForm.php in line 12. Requested URL: [...]/typo3conf/ext/easycaptcha/Classes/Service/Image.php?pid=1&identifier=easycaptcha-1 `

In the form definition, the capture element has got the default name 'easycaptcha-1', the same as in the error log.

**Comment by benjaminhirsch** [comment]
I've pushed  new changes, which should now work, even with a custom vendor dir @AKaravas. I'm going to release the new version now. I've implemented some kind of auto discovery, hopefully it will work. 😄 

@szerner Unfortunatly, with this new version, non composer based installations aren't supported anymore - sorry.
