### ISSUE TITLE
easycaptcha image not working if form is inserted as CE reference element

### ISSUE THREAD

**Issue by danielkoch** [columbusinteractive/typo3-easycaptcha#11]
Try to insert a form with a configured easycaptcha as a [reference element](https://www.typo3manual.com/typo3-manual-6/6-create-reference/61-creating-a-reference-element/).

The captcha image is not working:
Error 500: `typo3conf/ext/easycaptcha/Classes/Service/Image.php?pid=<no>&identifier=easycaptcha`

Environment:
TYPO3 `9.5.19`
easycaptcha: `1.2.2`

**Comment by benjaminhirsch** [comment]
Hey @danielkoch sorry for the late reply. Is this an TYPO3 installation in non composer mode, I'll have to tell you that we removed the support for non composer based installations.

Otherwhise please give the latest version 1.3.0 a shot, thank you! :)
