### ISSUE TITLE
README.md. Documentation - Own extension

### ISSUE THREAD

**Issue by AKaravas** [columbusinteractive/typo3-easycaptcha#12]
On the README.md doesn't mention anything about how we can implement the captcha in a custom fluid form (f:form). 

Would you mind adding it cause at this point, i have no idea how to implement it. I tried to copy the partial file to my partials, included it but i got errors.

This is what comes

![Screenshot_12](https://user-images.githubusercontent.com/16290719/94001110-561fc380-fd98-11ea-8422-580eb1a4bb00.png)

**Comment by benjaminhirsch** [comment]
For the time beeing, we removed support for use in custom extensions completley. Maybe this will change in a later version.
