### ISSUE TITLE
Question: How to style Relaod-button?

### ISSUE THREAD

**Issue by TomQv** [columbusinteractive/typo3-easycaptcha#16]
> The captcha field can be styled with the following CSS classes:
>     captcha-actions (Container for the action buttons e.g. reload or play)

Sorry, I'm still learning typo3.. where and how can I make the reload button small? Currently its huge, the whole width of the page.

**Comment by benjaminhirsch** [comment]
Hey @TomQv 

as written in the readme, both buttons a children of a div with the CSS class .captcha-actions. Also both buttons have a ID, tts-play and refresh-button. You can use CSS to apply any style you need. Where you add those styles (seperate css file, inline etc.)  is up to you. 😄 

Cheers,
Benjamin
