### ISSUE TITLE
Issue while inserting in third party extension

### ISSUE THREAD

**Issue by Gregor-Agnes** [columbusinteractive/typo3-easycaptcha#9]
Is there a way to include the captcha in a custom extension? I try to implement as an optional function here: https://extensions.typo3.org/extension/newsletter_subscribe/

 Currently I created a partial according to the EasyCaptcha Partial her, but when inserting it, I get:
`Argument 1 passed to TYPO3\CMS\Form\Hooks\FormElementHooks::beforeRendering() must be an instance of TYPO3\CMS\Form\Domain\Runtime\FormRuntime, null given, called in /var/www/typo3v10/public/typo3/sysext/form/Classes/ViewHelpers/RenderRenderableViewHelper.php on line 81`

Any hints, how to get it working?

I surely added
`            $captchaImage = PathUtility::getAbsoluteWebPath($captchaService->getDynamicImagePublicPath());
            $ttsHelperPath = PathUtility::getAbsoluteWebPath($captchaService->getTtsHelperPublicPath());
            $captchaImageAltAttribute = $captchaService->getCaptcha()->getImgAlt();
            $publicCaptchaPath = PathUtility::getAbsoluteWebPath($captchaService::getPublicCaptchaPath());
            $currentPid = $GLOBALS['TSFE']->getRequestedId();
`
in my controller and pass those to the view.

**Comment by benjaminhirsch** [comment]
Hey @Gregor-Agnes, sorry for the late reply. The partial provided here is surely only for the forms extension. However, in theory it should be possible to use the easycaptcha extension in you own extension. The only thing you really need need is the Captcha Sercvice Classes/Service/Captcha.php and implement the captcha rendering in a similar way we've done in the partial. That should be all. 

However, we have tested it currently only for use in the form extension itself, so there may be a problem hidden. :)

**Comment by benjaminhirsch** [comment]
For the time beeing, we removed support for use in custom extensions completley. Maybe this will change in a later version.
